import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SMIT Quiz Solution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-50 bg-fixed bg-center bg-[length:800px_800px] md:bg-[length:600px_600px] smm:bg-[length:400px_400px] bg-no-repeat ${inter.className} bg-[url('/smit.png')]`}>

        {children}
      </body>
    </html>
  );
}
