import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "SMIT Quiz Solution",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-slate-50  bg-fixed bg-center bg-contain  ${inter.className} bg-[url('https://th.bing.com/th/id/OIP.NkwEpqJktRs1GVY_474xRQHaHa?w=184&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7')]`} >
        {children}
      </body>
    </html>
  );
}
